#!/usr/bin/env node
/**
 * NASTRAN-93 Full Code Review — Phase 4 Case Study
 * Runs the hulde-review static analysis engine against all 1,728 Fortran files
 */

import { FortranPlugin } from '../hulde-review-plugin/packages/core/dist/plugins/fortran-plugin.js';
import { createDefaultRulesEngine } from '../hulde-review-plugin/packages/core/dist/review/rules-engine.js';
import { ReportGenerator } from '../hulde-review-plugin/packages/core/dist/review/report-generator.js';
import { readFileSync, writeFileSync, readdirSync, statSync, mkdirSync, existsSync } from 'fs';
import { join, relative } from 'path';

const NASTRAN_ROOT = '/Users/tarrysingh/Documents/GitHub/NASTRAN-93';
const OUTPUT_DIR = join(NASTRAN_ROOT, '.hulde-review');

// Recursively find all .f files
function findFortranFiles(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    if (entry === '.git' || entry === 'node_modules') continue;
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      findFortranFiles(full, files);
    } else if (entry.endsWith('.f')) {
      files.push(full);
    }
  }
  return files;
}

console.log('╔══════════════════════════════════════════════════════════╗');
console.log('║   HULDE REVIEW — NASA NASTRAN-93 Code Review            ║');
console.log('║   417,339 lines of FORTRAN IV/77 across 1,728 files     ║');
console.log('╚══════════════════════════════════════════════════════════╝');
console.log('');

const startTime = Date.now();

// Initialize
const plugin = new FortranPlugin();
const engine = createDefaultRulesEngine();
const allFindings = [];
let totalLines = 0;
let filesAnalyzed = 0;
let filesWithErrors = 0;
const fileSizes = [];

// Find all files
console.log('Phase 1 — Scanning...');
const files = findFortranFiles(NASTRAN_ROOT);
console.log(`  Found ${files.length} Fortran files`);
console.log('');

// Analyze each file
console.log('Phase 2 — Static Analysis...');
const progressInterval = Math.floor(files.length / 20); // Report every 5%

for (let i = 0; i < files.length; i++) {
  const filePath = files[i];
  const relPath = relative(NASTRAN_ROOT, filePath);

  try {
    const content = readFileSync(filePath, 'utf-8');
    const lines = content.split('\n').length;
    totalLines += lines;
    fileSizes.push({ path: relPath, lines });

    const structural = plugin.analyzeFile(relPath, content);
    const callGraph = plugin.extractCallGraph?.(relPath, content) ?? [];

    const findings = engine.analyze({
      filePath: relPath,
      content,
      language: 'fortran',
      structural,
      callGraph,
    });

    allFindings.push(...findings);
    filesAnalyzed++;
  } catch (err) {
    filesWithErrors++;
    if (filesWithErrors <= 5) {
      console.log(`  ⚠ Error analyzing ${relPath}: ${err.message}`);
    }
  }

  if ((i + 1) % progressInterval === 0) {
    const pct = Math.round(((i + 1) / files.length) * 100);
    console.log(`  ${pct}% — ${i + 1}/${files.length} files (${allFindings.length} findings so far)`);
  }
}

console.log(`  ✓ Analyzed ${filesAnalyzed} files (${filesWithErrors} errors)`);
console.log(`  ✓ Total findings: ${allFindings.length}`);
console.log('');

// Generate report
console.log('Phase 3 — Report Generation...');
const generator = new ReportGenerator();

// Build file→lines map for language breakdown
const fileLinesMap = new Map();
for (const { path, lines } of fileSizes) {
  fileLinesMap.set(path, lines);
}

const report = generator.generate({
  projectName: 'NASA NASTRAN-93',
  gitCommitHash: 'nasa/NASTRAN-93@master',
  totalFiles: filesAnalyzed,
  totalLines,
  languages: ['fortran'],
  findings: allFindings,
  fileLinesMap,
});

// Write output
if (!existsSync(OUTPUT_DIR)) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
}

writeFileSync(
  join(OUTPUT_DIR, 'review-report.json'),
  JSON.stringify(report, null, 2),
);

// Generate markdown report
const md = [];
md.push('# NASA NASTRAN-93 — Code Review Report');
md.push('');
md.push(`*Generated by [Hulde Review](https://hulde.ai) on ${new Date().toLocaleDateString()}*`);
md.push('');
md.push('## Executive Summary');
md.push('');
md.push(report.executiveSummary);
md.push('');
md.push('## Risk Score');
md.push('');
md.push(`**${report.summary.riskScore}/100** ${report.summary.riskScore > 70 ? '🔴 HIGH RISK' : report.summary.riskScore > 40 ? '🟡 MODERATE RISK' : '🟢 LOW RISK'}`);
md.push('');
md.push('## Summary');
md.push('');
md.push(`| Metric | Value |`);
md.push(`|---|---|`);
md.push(`| Total Files | ${filesAnalyzed} |`);
md.push(`| Total Lines | ${totalLines.toLocaleString()} |`);
md.push(`| Total Findings | ${report.summary.totalFindings} |`);
md.push(`| Technical Debt | ${report.summary.technicalDebtHours.toLocaleString()} hours |`);
md.push(`| Critical | ${report.summary.bySeverity.critical} |`);
md.push(`| High | ${report.summary.bySeverity.high} |`);
md.push(`| Medium | ${report.summary.bySeverity.medium} |`);
md.push(`| Low | ${report.summary.bySeverity.low} |`);
md.push(`| Info | ${report.summary.bySeverity.info} |`);
md.push('');
md.push('## Findings by Category');
md.push('');
md.push(`| Category | Count |`);
md.push(`|---|---|`);
for (const [cat, count] of Object.entries(report.summary.byCategory).sort((a, b) => b[1] - a[1])) {
  if (count > 0) md.push(`| ${cat} | ${count} |`);
}
md.push('');
md.push('## Top Risks');
md.push('');
for (const risk of report.summary.topRisks) {
  md.push(`- ${risk}`);
}
md.push('');
md.push('## Prioritized Recommendations');
md.push('');
for (const rec of report.recommendations) {
  md.push(`### ${rec.priority}. ${rec.title}`);
  md.push('');
  md.push(rec.description);
  md.push('');
  md.push(`- **Effort**: ${rec.estimatedEffort}`);
  md.push(`- **Impact**: ${rec.impact}`);
  md.push('');
}

// Top 20 worst files
md.push('## Top 20 Highest-Risk Files');
md.push('');
md.push(`| File | Findings | Worst Severity |`);
md.push(`|---|---|---|`);

const findingsByFile = {};
for (const f of allFindings) {
  if (!findingsByFile[f.filePath]) findingsByFile[f.filePath] = [];
  findingsByFile[f.filePath].push(f);
}

const severityOrder = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
const worstFiles = Object.entries(findingsByFile)
  .map(([path, findings]) => ({
    path,
    count: findings.length,
    worstSeverity: findings.reduce((worst, f) =>
      severityOrder[f.severity] < severityOrder[worst] ? f.severity : worst, 'info'),
  }))
  .sort((a, b) => {
    const sevDiff = severityOrder[a.worstSeverity] - severityOrder[b.worstSeverity];
    return sevDiff !== 0 ? sevDiff : b.count - a.count;
  })
  .slice(0, 20);

for (const f of worstFiles) {
  const icon = f.worstSeverity === 'critical' ? '🔴' : f.worstSeverity === 'high' ? '🟠' : '🟡';
  md.push(`| \`${f.path}\` | ${f.count} | ${icon} ${f.worstSeverity} |`);
}
md.push('');

// Top critical findings detail
md.push('## Critical Findings Detail');
md.push('');
const criticals = allFindings.filter(f => f.severity === 'critical').slice(0, 30);
for (const f of criticals) {
  md.push(`### 🔴 ${f.title}`);
  md.push('');
  md.push(`**File**: \`${f.filePath}\`${f.lineRange ? ` (lines ${f.lineRange[0]}-${f.lineRange[1]})` : ''}`);
  md.push('');
  md.push(f.description);
  if (f.suggestion) {
    md.push('');
    md.push(`**Suggestion**: ${f.suggestion}`);
  }
  md.push('');
}

md.push('---');
md.push('');
md.push('*Powered by [Hulde Review](https://hulde.ai) — AI-powered code review for enterprise codebases*');

writeFileSync(join(OUTPUT_DIR, 'review-report.md'), md.join('\n'));

const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);

console.log('');
console.log('╔══════════════════════════════════════════════════════════╗');
console.log('║                    RESULTS                               ║');
console.log('╠══════════════════════════════════════════════════════════╣');
console.log(`║  Risk Score:      ${String(report.summary.riskScore).padEnd(5)} / 100                          ║`);
console.log(`║  Total Findings:  ${String(report.summary.totalFindings).padEnd(38)}║`);
console.log(`║  Critical:        ${String(report.summary.bySeverity.critical).padEnd(38)}║`);
console.log(`║  High:            ${String(report.summary.bySeverity.high).padEnd(38)}║`);
console.log(`║  Medium:          ${String(report.summary.bySeverity.medium).padEnd(38)}║`);
console.log(`║  Low:             ${String(report.summary.bySeverity.low).padEnd(38)}║`);
console.log(`║  Info:            ${String(report.summary.bySeverity.info).padEnd(38)}║`);
console.log(`║  Tech Debt:       ${String(report.summary.technicalDebtHours.toLocaleString() + ' hours').padEnd(38)}║`);
console.log(`║  Time:            ${String(elapsed + 's').padEnd(38)}║`);
console.log('╠══════════════════════════════════════════════════════════╣');
console.log('║  Output:                                                 ║');
console.log('║  → .hulde-review/review-report.json                     ║');
console.log('║  → .hulde-review/review-report.md                       ║');
console.log('╚══════════════════════════════════════════════════════════╝');
